const defaultEmojiMap: Record<string, string> = {
  'airfryer': '🍟',
  'aloo gobi': '🥦',
  'aloo tikki': '🍔',
  'amaretto': '🍸',
  'American': '🍔',
  'aperol': '🍸',
  'appam': '🥘',
  'apple juice': '🍎',
  'apple': '🍎',
  'avocado toast': '🥑🍞',
  'avocado': '🥑',
  'bacon': '🥓',
  'bagel': '🥯',
  'baguette bread': '🥖',
  'baguette': '🥖',
  'baileys': '🥛',
  'baking powder': '🍞',
  'baking soda': '🍞',
  'banana': '🍌',
  'banchan': '🥢',
  'barbeque': '🍖',
  'basil leaves': '🌿',
  'basil': '🌿',
  'bay leaves': '🌿',
  'beans': '🍲',
  'beef tongue': '🍖',
  'beef': '🥩',
  'beer': '🍺',
  'beet juice': '🍆',
  'bell pepper': '🫑',
  'bellini': '🍹',
  'bhel puri': '🥗',
  'bibim naengmyeon': '🍜',
  'bibimbap': '🍚',
  'bingsu': '🍧',
  'birthday cake': '🎂',
  'biryani': '🍛',
  'bitter': '🍵',
  'bitters': '🍸',
  'blackberry': '🍇',
  'bloody mary': '🍹',
  'blue lagoon': '🍹',
  'blueberry': '🫐',
  'boba tea': '🧋',
  'boozy': '🍸',
  'brandy': '🥃',
  'bread': '🍞',
  'breakfast': '🍳',
  'brisket': '🍖',
  'broccoli': '🥦',
  'bubbles': '🥂',
  'budae jjigae': '🍲',
  'bulgogi': '🍖',
  'burger': '🍔',
  'burrito tortilla': '🌯',
  'burrito': '🌯',
  'butter': '🧈',
  'cabernet sauvignon': '🍷',
  'cake': '🎂',
  'campari': '🍸',
  'candy': '🍬',
  'cappuccino': '🥛',
  'caramel': '🍮',
  'carrot juice': '🥕',
  'carrot': '🥕',
  'celery stalk': '🌿',
  'chaat': '🍲',
  'chai': '☕',
  'champagne cocktail': '🍸',
  'champagne': '🍾',
  'chana chaat': '🥗',
  'chana masala': '🍛',
  'chardonnay': '🍷',
  'cheese wedge': '🧀',
  'cheese': '🧀',
  'cheeseburger': '🍔',
  'cherries': '🍒',
  'cherry': '🍒',
  'chicken drumstick': '🍗',
  'chicken tikka': '🍢',
  'chicken wing': '🍗',
  'chicken wings': '🍗',
  'chicken': '🍗',
  'chili pepper': '🌶️',
  'chili powder': '🌶️',
  'chimaek': '🍗🍺',
  'chimichanga': '🌯',
  'Chinese': '🥡',
  'chocolate bar': '🍫',
  'chocolate': '🍫',
  'chole bhature': '🥯',
  'chorizo': '🌭',
  'cilantro': '🌿',
  'cinnamon': '🍮',
  'clam': '🐚',
  'clamato': '🍅',
  'clams': '🐚',
  'cocktail onion': '🧅',
  'cocktail': '🍸',
  'coffee': '☕',
  'cookie': '🍪',
  'coriander': '🍛',
  'corn tortilla': '🌽',
  'corn': '🌽',
  'corned beef': '🍖',
  'cosmopolitan': '🍸',
  'cotton candy': '🍥',
  'crab': '🦀',
  'cranberry juice': '🍒',
  'creamy': '🥛',
  'croissant': '🥐',
  'croquette': '🍢',
  'crunchy': '🍪',
  'cucumber': '🥒',
  'cumin': '🍛',
  'cupcake': '🧁',
  'curry powder': '🍛',
  'curry': '🍛',
  'custard': '🍮',
  'dahi puri': '🍲',
  'daiquiri': '🍹',
  'dal makhani': '🥘',
  'dango': '🍡',
  'date': '📅',
  'dhokla': '🧊',
  'dill': '🌿',
  'dim sum': '🥟',
  'dinner': '🍲',
  'donut': '🍩',
  'dosa': '🥞',
  'double cheeseburger': '🍔🧀🍔',
  'dragon fruit': '🐉🍇',
  'duck': '🦆',
  'dumpling wrapper': '🥟',
  'dumpling': '🥟',
  'earl grey tea': '☕️',
  'eggnog': '🥚🍶',
  'eggplant': '🍆',
  'eggs': '🍳',
  'elderflower': '🍃🌼',
  'enchilada': '🌯',
  'espresso': '☕',
  'fajita': '🫔',
  'falafel': '🧆',
  'farfalle pasta': '🦋🍝',
  'fettuccine alfredo': '🍝🧀',
  'fig': '🌰🍯',
  'filet mignon': '🥩',
  'fish and chips': '🍟🐟',
  'fish': '🐟',
  'fizzy drink': '🥤',
  'flan': '🍮',
  'flatbread': '🍞',
  'flour tortilla': '🍞',
  'flour': '🌾',
  'foie gras': '🦆🍞',
  'fondue': '🧀🫕',
  'fortune cookie': '🥠',
  'french fries': '🍟',
  'french toast': '🍞🍳',
  'French': '🥐',
  'fried chicken': '🍗',
  'fried egg': '🍳',
  'fried rice': '🍚',
  'fried shrimp': '🍤',
  'fries': '🍟',
  'frozen yogurt': '🍦',
  'fruit punch': '🍹',
  'fruit': '🍇',
  'fruity': '🍇',
  'galbi': '🍖',
  'garlic bread': '🍞🧄',
  'garlic': '🧄',
  'gimbap': '🍣',
  'gin and tonic': '🍸',
  'gin': '🍸',
  'ginger ale': '🍺',
  'ginger beer': '🍺',
  'ginger': '🌿',
  'gluten': '🌾',
  'gluten-free': '🌾',
  'gnocchi': '🥔',
  'goat cheese': '🐐🧀',
  'grape juice': '🍇',
  'grapefruit juice': '🍊',
  'grapefruit': '🍊',
  'grapes': '🍇',
  'green sauce': '🌿',
  'grenadine': '🍹',
  'grilled cheese': '🍞🧀',
  'grilled fish': '🐟',
  'grilled vegetables': '🌶️🥦🥕',
  'guacamole': '🥑🍅',
  'gulab jamun': '🍬',
  'gummy bear': '🐻',
  'gyoza': '🥟',
  'gyudon': '🍚',
  'haemul pajeon': '🍲',
  'halal': '🥙',
  'ham': '🍖',
  'hamburger': '🍔',
  'hazelnut': '🌰',
  'herbaceous': '🌿',
  'herbs': '🌿',
  'honey': '🍯',
  'hot chocolate': '☕️🍫',
  'hot cocoa': '☕️🍫',
  'hot dog': '🌭',
  'hot sauce': '🌶️',
  'hotdog': '🌭',
  'hotteok': '🥞',
  'ice cream cone': '🍦',
  'ice cream': '🍨',
  'ice': '🧊',
  'iced coffee': '☕️🧊',
  'iced tea': '🧊',
  'idli': '🍚',
  'Indian': '🍛',
  'indian': '🥘',
  'instant pot': '🍲',
  'irish coffee': '☕',
  'Italian': '🍝',
  'jajang tteokbokki': '🍢',
  'jajangmyeon': '🍜',
  'jalapeno': '🌶️',
  'jambalaya': '🥘',
  'jamun juice': '🍇',
  'Japanese': '🍱',
  'japanese': '🍱',
  'japchae': '🍝',
  'jjamppong': '🍜',
  'juice': '🧃',
  'juicy': '🍊',
  'kabab': '🍢',
  'kakigori': '🍧',
  'kalguksu': '🍜',
  'katsu curry': '🍛',
  'ketchup': '🍅',
  'kimbap': '🍣',
  'kimchi': '🥬',
  'kiwi': '🥝',
  'kombucha': '🍶',
  'lamb chop': '🍖',
  'lamb': '🐑',
  'lassi': '🥛',
  'latte': '🥛',
  'lemon juice': '🍋',
  'lemon': '🍋',
  'lemonade': '🍋',
  'lettuce': '🥬',
  'lime juice': '🍋',
  'lime': '🥭',
  'liqueur': '🍸',
  'lobster': '🦞',
  'lollipop': '🍭',
  'long island iced tea': '🍹',
  'lunch': '🍔',
  'macchiato': '☕',
  'mai tai': '🍹',
  'makgeolli': '🍺',
  'malbec': '🍷',
  'mandu': '🥟',
  'mango': '🥭',
  'manhattan': '🍸',
  'maple syrup': '🍁',
  'margarita': '🍹',
  'martini': '🍸',
  'masala dosa': '🍲',
  'matcha': '🍵',
  'mayonnaise': '🍴',
  'meat': '🥩',
  'meatball': '🍲',
  'meatloaf': '🍞',
  'medium': '🌶️',
  'melon': '🍈',
  'melonpan': '🍞',
  'merlot': '🍷',
  'Mexican': '🌮',
  'mezcal': '🍸',
  'michelada': '🍺',
  'microwave': '🍿',
  'mild': '🧅',
  'milk': '🥛',
  'milkshake': '🥤',
  'mimosa': '🍹',
  'mint leaves': '🌿',
  'mint': '🌿',
  'misal pav': '🍛',
  'mocha': '🍫',
  'mochi': '🍡',
  'mojito': '🍹',
  'moscato': '🍷',
  'moscow mule': '🍸',
  'mul naengmyeon': '🍜',
  'mule': '🍸',
  'mushroom': '🍄',
  'mussels': '🐚',
  'mustard': '🧂',
  'naan': '🍞',
  'nachos': '🧀',
  'naengmyeon': '🍜',
  'negroni': '🍸',
  'non-alcoholic': '🍹',
  'noodles': '🍜',
  'nutmeg': '🧄',
  'octopus': '🐙',
  'oden': '🍢',
  'oil': '🫒',
  'old fashioned': '🥃',
  'olive oil': '🫒',
  'olive': '🫒',
  'onigiri': '🍙',
  'onion rings': '🧅',
  'onion': '🧅',
  'orange juice': '🍊',
  'orange zest': '🍊',
  'orange': '🍊',
  'oregano': '🌿',
  'oven': '🍪',
  'oyster': '🦪',
  'oysters': '🐚',
  'pad thai': '🍝',
  'pakora': '🥗',
  'paleo': '🦕',
  'pancake': '🥞',
  'paneer tikka': '🍢',
  'papaya': '🧡',
  'paratha': '🥞',
  'parsley': '🌿',
  'passion fruit': '🍓',
  'pastrami': '🍖',
  'pav bhaji': '🍛',
  'peach': '🍑',
  'peanuts': '🥜',
  'pear': '🍐',
  'pepper': '🧂',
  'pepperoni': '🍕',
  'pho': '🍲',
  'pico de gallo': '🧅',
  'pie': '🥧',
  'pina colada': '🍹',
  'pineapple juice': '🍍',
  'pineapple': '🍍',
  'pinot noir': '🍷',
  'pizza slice': '🍕',
  'pizza': '🍕',
  'piña colada': '🍹',
  'poha': '🥣',
  'poke bowl': '🍲',
  'popcorn bucket': '🍿🍿',
  'popcorn': '🍿',
  'pork chop': '🍖',
  'pork tenderloin': '🍖',
  'pork': '🍖',
  'port': '🍷',
  'potato': '🥔',
  'pretzel': '🥨',
  'prosciutto': '🍖',
  'pudding': '🍮',
  'pulled pork': '🍖',
  'quesadilla': '🧀🌮',
  'queso': '🧀',
  'ramen bowl': '🍜',
  'ramen': '🍜',
  'ramune': '🍾',
  'ramyun': '🍜',
  'raspberry': '🍇',
  'red sauce': '🍅',
  'red wine': '🍷',
  'refreshing': '🥤',
  'ribs': '🍖',
  'rice': '🍚',
  'rioja': '🍷',
  'roast beef': '🍖',
  'roast pork': '🍖',
  'rosemary sprig': '🌿',
  'rosemary': '🌿',
  'rosé wine': '🍷',
  'rum': '🍹',
  'saag paneer': '🧀',
  'saffron': '🍛',
  'sage': '🌿',
  'sake': '🍶',
  'salad': '🥗',
  'salami': '🍖',
  'salmon': '🐟',
  'salsa verde': '🍅',
  'salsa': '🍅',
  'salt and pepper': '🧂',
  'salt': '🧂',
  'salty': '🧂',
  'sambuca': '🍸',
  'samgyeopsal': '🥓',
  'samosa': '🥟',
  'sandwich': '🥪',
  'sashimi': '🍣',
  'sausage': '🌭',
  'sauvignon blanc': '🍷',
  'screwdriver': '🍹',
  'sex on the beach': '🍹',
  'shaved ice': '🍧',
  'shellfish': '🦐',
  'sherry': '🍷',
  'shirley temple': '🍹',
  'shot': '🥃',
  'shrimp': '🦐',
  'sikhye': '🥛',
  'slow cooker': '🥘',
  'smoky': '🔥',
  'smoothie': '🍹',
  'snack': '🍪',
  'soba': '🍜',
  'soda water': '🥤',
  'soda': '🥤',
  'soju': '🍶',
  'soup': '🥣',
  'sour cream': '🍶',
  'sour': '🍋',
  'soy sauce': '🍱',
  'soy': '🌱',
  'spaghetti': '🍝',
  'spices': '🧂',
  'spicy': '🌶️',
  'spring roll': '🍱',
  'squid': '🦑',
  'steak': '🥩',
  'stovetop': '🍳',
  'strawberry daiquiri': '🍹',
  'strawberry': '🍓',
  'sugar syrup': '🍯',
  'sugar': '🍬',
  'sukiyaki': '🥩',
  'sundubu-jjigae': '🍲',
  'sushi roll': '🍣',
  'sushi': '🍣',
  'sweet potato': '🍠',
  'sweet': '🍯',
  'syrah': '🍷',
  'taco shell': '🌮',
  'taco': '🌮',
  'takoyaki': '🐙',
  'tandoori chicken': '🍗',
  'tandoori': '🫓',
  'tangy': '🍅',
  'tea': '🍵',
  'tempranillo': '🍷',
  'tempura': '🍤',
  'tequila sunrise': '🍹',
  'tequila': '🍸',
  'Thai': '🍛',
  'thali': '🍽️',
  'thyme sprig': '🌿',
  'thyme': '🌿',
  'tiramisu': '🍰',
  'tomato juice': '🍅',
  'tomato': '🍅',
  'tonic water': '🥤',
  'tortilla chips': '🌽',
  'tortilla': '🌮',
  'tree nuts': '🌰',
  'tteok-galbi': '🍖',
  'tteokbokki': '🍢',
  'tuna': '🐟',
  'turkey': '🦃',
  'turmeric': '🧡',
  'udon': '🍲',
  'umami': '🍄',
  'uttapam': '🥘',
  'vada pav': '🍔',
  'vada': '🥟',
  'vanilla extract': '🎂',
  'vegan': '🌿',
  'vegetarian': '🥕',
  'vermouth': '🍸',
  'vinegar': '🍾',
  'vodka tonic': '🍸',
  'vodka': '🍸',
  'waffle': '🧇',
  'water': '💧',
  'watermelon': '🍉',
  'wheat': '🌾',
  'whiskey sour': '🥃',
  'whiskey': '🥃',
  'white wine': '🍷',
  'whole30': '🥦',
  'wine': '🍷',
  'yakiniku': '🍖',
  'yangnyeom chicken': '🍗',
  'yogurt': '🍦',
  'zesty': '🍋',
  'zinfandel': '🍷',
  'zucchini': '🥒',
};
export default defaultEmojiMap;